const UPDATE_SETTINGS_PARAMS = 'SETTINGS/UPDATE_SETTINGS_PARAMS';
const UPDATE_AUTHORIZATION = 'SETTINGS/UPDATE_AUTHORIZATION';
const UPDATE_BLACK_LIST = 'SETTINGS/UPDATE_BLACK_LIST';
const UPDATE_DISPLAY_SETTINGS = 'SETTINGS/UPDATE_DISPLAY_SETTINGS';

export { UPDATE_SETTINGS_PARAMS, UPDATE_AUTHORIZATION, UPDATE_BLACK_LIST, UPDATE_DISPLAY_SETTINGS };
