const UPDATE_SETTINGS_PARAMS = 'SETTINGS/UPDATE_SETTINGS_PARAMS';
const UPDATE_AUTHORIZATION = 'SETTINGS/UPDATE_AUTHORIZATION';
const UPDATE_BLACK_LIST = 'SETTINGS/UPDATE_BLACK_LIST';

export { UPDATE_SETTINGS_PARAMS, UPDATE_AUTHORIZATION, UPDATE_BLACK_LIST };
